services:
  rabbitmq:
    image: rd.clouditera.com/library/rabbitmq:4.1.3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: clouditera
      RABBITMQ_DEFAULT_PASS: clouditera
    ports:
      - "${RABBITMQ_AMQP_PORT:-10004}:5672"    # AMQP 协议端口
      - "${RABBITMQ_UI_PORT:-10005}:15672"   # Web 管理控制台端口
    restart: unless-stopped