services:
  redis_service:
    image: rd.clouditera.com/sca-sast-lib/library/redis:7.2.0
    restart: always
    volumes:
      - ${INSTALL_LOCAL}/redis:/data
    command: [ "redis-server", "--appendonly", "yes", "--requirepass", "$REDIS_PASSWORD" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
    ports:
      - "${REDIS_PORT:-10003}:${CONTAINER_PORT:-6379}"
