

DROP TABLE IF EXISTS `PAPER_JOURNAL_TYPE`;
DROP TABLE IF EXISTS `PAPER_SCHEDULED_CONFIG`;
DROP TABLE IF EXISTS `PAPER_ANALYSIS_INFO`;
DROP TABLE IF EXISTS `PAPER_FILE_INFO`;
DROP TABLE IF EXISTS `PAPER_KEYWORDS`;

-- 论文检索新增顶会表
CREATE TABLE `PAPER_JOURNAL_TYPE` (
  `ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '主键ID',
  `NAME` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '名称',
  `JOURNAL_COUNT` int DEFAULT NULL COMMENT '顶会数量',
  `SORT` int DEFAULT NULL COMMENT '排序',
  `START_TIME` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '开始时间',
  `END_TIME` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '结束时间',
  `CREATED_TIME` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `CREATED_BY` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '创建人',
  `UPDATED_TIME` timestamp NULL DEFAULT NULL COMMENT '最后一次时间',
  `UPDATED_BY` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '最后一次修改人',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='安全论文检索-期刊类型';


-- 论文检索新增定时任务表
CREATE TABLE `PAPER_SCHEDULED_CONFIG` (
  `ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '主键ID',
  `ENABLED` tinyint DEFAULT NULL COMMENT '是否启用',
  `LAST_TIME` datetime(6) DEFAULT NULL COMMENT '上一次执行时间',
  `INTERVAL_SECONDS` bigint DEFAULT NULL COMMENT '间隔时间(秒)',
  `UPLOAD_RAG_ENABLED` tinyint DEFAULT NULL COMMENT '是否同步rag文档',
  `CREATED_TIME` datetime(6) DEFAULT NULL COMMENT '创建时间',
  `CREATED_BY` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '创建人',
  `UPDATED_TIME` datetime(6) DEFAULT NULL COMMENT '更新时间',
  `UPDATED_BY` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='安全论文检索-定时任务配置表';

-- 论文检索新增论文信息表
CREATE TABLE `PAPER_ANALYSIS_INFO` (
  `FILE_MD5` varchar(255) NOT NULL COMMENT '跟主表关联',
  `LANGUAGE` enum('EN','ZH','OTHER') NOT NULL COMMENT '论文语言',
  `TITLE` varchar(500) NOT NULL COMMENT '论文标题',
  `ABSTRACT` varchar(3500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '论文摘要',
  `TITLE_ZH` varchar(500) DEFAULT NULL COMMENT '论文中文标题',
  `ABSTRACT_ZH` varchar(3500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '论文中文摘要',
  `OPENSOURCE_CODE_URL` varchar(2000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '文章内 开源代码url',
  `PAPER_TYPE` enum('1','2','3','4') NOT NULL COMMENT '论文类型，1-Survey，2-Theory，3-Application，4-Dataset_Benchmark',
  `AI_ABSTRACT` varchar(3000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT 'AI生成的文章摘要',
  `AI_NOTE` longtext NOT NULL COMMENT 'AI笔记',
  `CONTENT_QUALITY_SCORE` varchar(2000) NOT NULL COMMENT '内容评分',
  `RECOMMENDED_QA` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '生成的3个QA对',
  PRIMARY KEY (`FILE_MD5`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='论文信息表';

CREATE TABLE `PAPER_FILE_INFO` (
  `ID` int NOT NULL AUTO_INCREMENT COMMENT '自增 ID',
  `CREATE_TIME` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '数据创建时间',
  `FILE_MD5` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '文件 MD5 唯一标识',
  `FILE_EXT` varchar(20) NOT NULL COMMENT '文件后缀格式',
  `FILE_COLLECTION_TIME` datetime DEFAULT NULL COMMENT 'DBLP文档收录时间',
  `FILE_CREATED_TIME` datetime DEFAULT NULL COMMENT '文档在系统内的创建时间',
  `FILE_MODIFIED_TIME` datetime DEFAULT NULL COMMENT '文档在系统内的修改时间',
  `PUBLISH_TIME` varchar(255) DEFAULT NULL COMMENT '论文发表时间',
  `AUTHOR` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '论文作者',
  `JOURNAL_SOURCE_ABBREVIATION` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '期刊来源简称',
  `JOURNAL_SOURCE_FULL` varchar(255) DEFAULT NULL COMMENT '期刊来源全称',
  `DOI` varchar(255) DEFAULT NULL COMMENT '论文唯一 DOI',
  `SOURCE_TYPE` enum('1','2') NOT NULL COMMENT '文件来源类型：1-用户上传，2-网络采集',
  `SOURCE_URL` varchar(1024) DEFAULT NULL COMMENT '论文原文链接或者下载 URL',
  `NUM_PAGES` int DEFAULT NULL COMMENT 'PDF 页数',
  `PARSED_CONTENT` longtext COMMENT 'MinerU 解析出来的内容',
  `STORAGE_PATH` varchar(1024) DEFAULT NULL COMMENT 'PDF 文件本地存储路径',
  `PDF_FORMAT` varchar(255) DEFAULT NULL COMMENT 'PDF 文件版本号',
  `PDF_CREATOR` varchar(1024) DEFAULT NULL COMMENT '生成 PDF 时所使用的软件工具链',
  `PDF_PRODUCER` varchar(1024) DEFAULT NULL COMMENT 'PDF 生成软件/工具链的生产者信息',
  `PDF_ENCRYPTION` varchar(255) DEFAULT NULL COMMENT '是否启用了加密',
  `RAG_DOC_ID` varchar(128) DEFAULT NULL COMMENT 'RAG 文档ID',
  `RAG_DOC_PATH` varchar(1024) DEFAULT NULL COMMENT 'RAG 文档路径',
  `RAG_KB_ID` varchar(128) DEFAULT NULL COMMENT 'RAG 知识库ID',
  `RAG_AINOTE_DOC_ID` varchar(255) DEFAULT NULL COMMENT 'RAG AINOTE 知识库文档ID',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=7626 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='论文文件信息表';

CREATE TABLE `PAPER_KEYWORDS` (
  `FILE_MD5` varchar(255) NOT NULL COMMENT '跟主表关联',
  `KEY_WORD1` varchar(255) NOT NULL COMMENT '关键词1',
  `EXPLANATION1` varchar(500) NOT NULL COMMENT '解释1',
  `KEY_WORD2` varchar(255) NOT NULL COMMENT '关键词2',
  `EXPLANATION2` varchar(500) NOT NULL COMMENT '解释2',
  `KEY_WORD3` varchar(255) NOT NULL COMMENT '关键词3',
  `EXPLANATION3` varchar(500) NOT NULL COMMENT '解释3',
  `KEY_WORD4` varchar(255) NOT NULL COMMENT '关键词4',
  `EXPLANATION4` varchar(500) NOT NULL COMMENT '解释4',
  `KEY_WORD5` varchar(255) NOT NULL COMMENT '关键词5',
  `EXPLANATION5` varchar(500) NOT NULL COMMENT '解释5',
  PRIMARY KEY (`FILE_MD5`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='存储5个关键词和解释表';
