DROP TABLE IF EXISTS `SAFETY_INFORMATION_TOPIC_REL`;
DROP TABLE IF EXISTS `SAFETY_INFORMATION_TOPIC`;
DROP TABLE IF EXISTS `SAFETY_INFORMATION_TAG_REL`;
DROP TABLE IF EXISTS `SAFETY_INFORMATION_TAG`;
DROP TABLE IF EXISTS `SAFETY_INFORMATION_SOURCE_TYPE_REL`;
DROP TABLE IF EXISTS `SAFETY_INFORMATION_SOURCE_TYPE`;
DROP TABLE IF EXISTS `SAFETY_INFORMATION_SOURCE`;
DROP TABLE IF EXISTS `SAFETY_INFORMATION_SCHEDULED_CONFIG`;
DROP TABLE IF EXISTS `SAFETY_INFORMATION`;
-- clouditera_aigc.SAFETY_INFORMATION definition

CREATE TABLE `SAFETY_INFORMATION` (
  `ID` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '主键ID',
  `CREATED_TIME` datetime(6) DEFAULT NULL COMMENT '创建时间',
  `CREATED_BY` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '创建人',
  `UPDATED_TIME` datetime(6) DEFAULT NULL COMMENT '更新时间',
  `UPDATED_BY` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '更新人',
  `ORIGINAL_CONTENT` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '资讯原文',
  `SUMMARY_CONTENT` text COLLATE utf8mb4_unicode_ci COMMENT '总结内容',
  `ORIGINAL_TITLE` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '原文标题',
  `SUMMARY_TITLE` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '总结标题',
  `ORIGINAL_URL` text COLLATE utf8mb4_unicode_ci COMMENT '原文链接',
  `RELEASE_TIME` datetime(6) DEFAULT NULL COMMENT '发布时间',
  `SOURCE_ID` bigint DEFAULT NULL COMMENT '来源ID',
  `PIC` text COLLATE utf8mb4_unicode_ci COMMENT '图片地址',
  `SUMMARY_STATUS` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '总结状态',
  `SUMMARY_COUNT` int DEFAULT NULL COMMENT '总结次数',
  `SCORE` float DEFAULT NULL COMMENT 'AI 评分',
  `ORIGINAL_CONTENT_LENGTH` int DEFAULT NULL COMMENT '原文长度',
  `SUMMARY_ONE_LINE` text COLLATE utf8mb4_unicode_ci COMMENT '一句话总结',
  `SUMMARY_EXCERPT` text COLLATE utf8mb4_unicode_ci COMMENT '总结摘要',
  `CRAWLER_ID` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '爬虫ID',
  PRIMARY KEY (`ID`),
  KEY `SAFETY_INFORMATION_SOURCE_ID_IDX` (`SOURCE_ID`) USING BTREE,
  KEY `SAFETY_INFORMATION_RELEASE_TIME_IDX` (`RELEASE_TIME`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='安全资讯表';


-- clouditera_aigc.SAFETY_INFORMATION_SCHEDULED_CONFIG definition

CREATE TABLE `SAFETY_INFORMATION_SCHEDULED_CONFIG` (
  `ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '主键ID',
  `ENABLED` tinyint DEFAULT NULL COMMENT '是否启用',
  `LAST_TIME` datetime(6) DEFAULT NULL COMMENT '上一次执行时间',
  `INTERVAL_SECONDS` bigint DEFAULT NULL COMMENT '间隔时间(秒)',
  `CREATED_TIME` datetime(6) DEFAULT NULL COMMENT '创建时间',
  `CREATED_BY` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '创建人',
  `UPDATED_TIME` datetime(6) DEFAULT NULL COMMENT '更新时间',
  `UPDATED_BY` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='安全资讯定时任务配置表';


-- clouditera_aigc.SAFETY_INFORMATION_SOURCE definition

CREATE TABLE `SAFETY_INFORMATION_SOURCE` (
  `ID` bigint NOT NULL COMMENT '主键ID',
  `NAME` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '名称',
  `SORT` int DEFAULT NULL COMMENT '排序',
  `CREATED_TIME` datetime(6) DEFAULT NULL,
  `CREATED_BY` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `UPDATED_TIME` datetime(6) DEFAULT NULL,
  `UPDATED_BY` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='安全资讯来源';


-- clouditera_aigc.SAFETY_INFORMATION_SOURCE_TYPE definition

CREATE TABLE `SAFETY_INFORMATION_SOURCE_TYPE` (
  `ID` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '主键ID',
  `NAME` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '名称',
  `SORT` int DEFAULT NULL COMMENT '排序',
  `CREATED_TIME` datetime(6) DEFAULT NULL COMMENT '创建时间',
  `CREATED_BY` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '创建人',
  `UPDATED_TIME` datetime(6) DEFAULT NULL COMMENT '更新时间',
  `UPDATED_BY` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- clouditera_aigc.SAFETY_INFORMATION_SOURCE_TYPE_REL definition

CREATE TABLE `SAFETY_INFORMATION_SOURCE_TYPE_REL` (
  `ID` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '主键ID',
  `SOURCE_ID` bigint DEFAULT NULL COMMENT '资讯源ID',
  `SOURCE_TYPE_ID` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '资讯源类型ID',
  `CREATED_TIME` datetime(6) DEFAULT NULL COMMENT '创建时间',
  `CREATED_BY` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '创建人',
  `UPDATED_TIME` datetime(6) DEFAULT NULL COMMENT '更新时间',
  `UPDATED_BY` varchar(65) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='安全资讯源与类型关联表';


-- clouditera_aigc.SAFETY_INFORMATION_TAG definition

CREATE TABLE `SAFETY_INFORMATION_TAG` (
  `ID` bigint NOT NULL COMMENT '主键ID',
  `NAME` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '标签名称',
  `CREATED_TIME` datetime(6) DEFAULT NULL COMMENT '创建时间',
  `CREATED_BY` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '创建人',
  `UPDATED_TIME` datetime(6) DEFAULT NULL COMMENT '更新时间',
  `UPDATED_BY` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='安全资讯标签表';


-- clouditera_aigc.SAFETY_INFORMATION_TAG_REL definition

CREATE TABLE `SAFETY_INFORMATION_TAG_REL` (
  `ID` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '主键ID',
  `SAFETY_INFORMATION_ID` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '安全资讯ID',
  `SAFETY_INFORMATION_TAG_ID` bigint DEFAULT NULL COMMENT '安全资讯标签ID',
  `CREATED_TIME` datetime(6) DEFAULT NULL COMMENT '创建时间',
  `CREATED_BY` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '创建人',
  `UPDATED_TIME` datetime(6) DEFAULT NULL COMMENT '更新时间',
  `UPDATED_BY` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '更新人'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='安全资讯标签关联表';


-- clouditera_aigc.SAFETY_INFORMATION_TOPIC definition

CREATE TABLE `SAFETY_INFORMATION_TOPIC` (
  `ID` bigint NOT NULL COMMENT '主键ID',
  `NAME` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '专题名称',
  `SORT` int DEFAULT NULL COMMENT '排序',
  `CREATED_TIME` datetime(6) DEFAULT NULL COMMENT '创建时间',
  `CREATED_BY` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '创建人',
  `UPDATED_TIME` datetime(6) DEFAULT NULL COMMENT '更新时间',
  `UPDATED_BY` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='安全资讯专题分类表';


-- clouditera_aigc.SAFETY_INFORMATION_TOPIC_REL definition

CREATE TABLE `SAFETY_INFORMATION_TOPIC_REL` (
  `ID` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '主键ID',
  `SAFETY_INFORMATION_ID` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '资讯ID',
  `SAFETY_INFORMATION_TOPIC_ID` bigint DEFAULT NULL COMMENT '专题ID',
  `CREATED_TIME` datetime(6) DEFAULT NULL COMMENT '创建时间',
  `CREATED_BY` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '创建人',
  `UPDATED_TIME` datetime(6) DEFAULT NULL COMMENT '更新时间',
  `UPDATED_BY` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='资讯专题关联表';