-- AGENT表新增字段
ALTER TABLE `clouditera_aigc`.`AGENT` 
ADD COLUMN `AGENT_METADATA` text NULL COMMENT '智能体元数据配置' AFTER `PARENT_ID`;

UPDATE AGENT SET AGENT_METADATA = '{"agentHasDes":1,"desOnLine":0}' WHERE ID IN ('3','13','4');

-- AGENT表新增安全论文检索智能体数据
INSERT INTO `clouditera_aigc`.`AGENT` (`ID`, `AGENT_NAME`, `WORKFLOW_NAME`, `AGENT_TYPE`, `TAG`, `PROMPT`, `APP_ID`, `FLAG`, `SORT`, `SHORTCUT`, `KL_STATUS`, `KEY`, `CREATED_TIME`, `CREATED_BY`, `UPDATED_TIME`, `UPDATED_BY`, `MODE_TYPE`, `CONFIG`, `VERSION`, `STATUS`, `TYPE`, `COUNT_TOKENS`, `COMMON_HOME`, `COMMON_CONVERSATION`, `COMMON_QUESTION`, `PARENT_ID`, `AGENT_METADATA`) VALUES ('24', '安全论文检索', '安全论文检索', 'PAPER_RETRIEVE', 'PAPER_RETRIEVE', NULL, '1f9632fd-9985-492c-9df6-f05c47e85a16', 1, 24, 0, 0, 'app-GDHvUXtlaVSaFvfYK2sdebO0', NULL, NULL, '2025-08-26 17:01:51', '2d8c6945-a3b4-43c1-9dcc-d21a4e780d99', 'CHAT_WORKFLOW', '{\"database\":[],\"llm\":[]}', '1.0', 'AGENT_ALPHA', 'KNOWLEDGE', 1, 1, 1, 0, NULL, 'null');
INSERT INTO `clouditera_aigc`.`AGENT` (`ID`, `AGENT_NAME`, `WORKFLOW_NAME`, `AGENT_TYPE`, `TAG`, `PROMPT`, `APP_ID`, `FLAG`, `SORT`, `SHORTCUT`, `KL_STATUS`, `KEY`, `CREATED_TIME`, `CREATED_BY`, `UPDATED_TIME`, `UPDATED_BY`, `MODE_TYPE`, `CONFIG`, `VERSION`, `STATUS`, `TYPE`, `COUNT_TOKENS`, `COMMON_HOME`, `COMMON_CONVERSATION`, `COMMON_QUESTION`, `PARENT_ID`, `AGENT_METADATA`) VALUES ('118', '安全论文检索', '摘要总结', 'PAPER_RETRIEVE', 'PAPER_RETRIEVE', NULL, '4b0e7737-3012-47fa-a3ae-3aa545e70885', 0, 118, 0, 0, 'app-sHItm3PG1LWuiukfdCibCFWu', NULL, NULL, '2025-07-16 10:02:18', 'ff6c23a8-47c5-46a9-b3c5-8d9c3df4c1bf', 'WORKFLOW', '{\"database\":[],\"llm\":[]}', '1.0', 'AGENT_ALPHA', 'KNOWLEDGE', 1, 1, 1, 0, NULL, NULL);

INSERT INTO `clouditera_aigc`.`DATASETS` (`ID`, `AGENT_ID`, `DATASETS_ID`, `NAME`, `STATUS`, `ALL`, `SHOW`, `CREATED_TIME`, `CREATED_BY`, `UPDATED_TIME`, `UPDATED_BY`) VALUES ('24', '24', NULL, '安全论文检索', 0, 0, 1, '2024-04-17 09:52:29', 'admin', '2024-04-17 09:52:29', 'admin');

UPDATE `clouditera_aigc`.`AGENT` SET FLAG = 0 where id = "11";
DELETE FROM AGENT_SHORTCUT WHERE AGENT_ID = "11";