services:
  postgres:
    image: rd.clouditera.com/library/pgvector:pg17
    restart: always
    volumes:
      - ${INSTALL_LOCAL}/pgdata:/var/lib/postgresql/data
      - ../../_data/base/postgresql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${PG_PORT:-10002}:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 60s
      retries: 3
