ALTER TABLE `clouditera_aigc`.`PAPER_JOURNAL_TYPE` 
ADD COLUMN `CCF_LEVEL` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'ccf等级' AFTER `END_TIME`;

ALTER TABLE `clouditera_aigc`.`PAPER_FILE_INFO`
    ADD COLUMN `PUBLISH_YEAR` INT GENERATED ALWAYS AS (CAST(NULLIF(SUBSTRING_INDEX(`PUBLISH_TIME`, '-', 1), '') AS UNSIGNED)) VIRTUAL AFTER `RAG_AINOTE_DOC_ID`,
    ADD COLUMN `AUTHOR_TEXT` TEXT GENERATED ALWAYS AS (TRIM(REGEXP_REPLACE(`AUTHOR`, '[\\[\\]"]|,', ' '))) STORED AFTER `PUBLISH_YEAR`,
    ADD COLUMN `CCF_LEVEL` ENUM('A', 'B', 'C', 'OTHER') DEFAULT NULL COMMENT 'CCF等级' AFTER `AUTHOR_TEXT`;
