ALTER TABLE `clouditera_aigc`.`PAPER_JOURNAL_TYPE` 
ADD COLUMN `CCF_LEVEL` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL DEFAULT NULL COMMENT 'ccf等级' AFTER `END_TIME`;

ALTER TABLE `clouditera_aigc`.`PAPER_FILE_INFO`
    ADD COLUMN `PUBLISH_YEAR` INT GENERATED ALWAYS AS (CAST(NULLIF(SUBSTRING_INDEX(`PUBLISH_TIME`, '-', 1), '') AS UNSIGNED)) VIRTUAL AFTER `RAG_AINOTE_DOC_ID`,
    ADD COLUMN `AUTHOR_TEXT` TEXT GENERATED ALWAYS AS (TRIM(REGEXP_REPLACE(`AUTHOR`, '[\\[\\]"]|,', ' '))) STORED AFTER `PUBLISH_YEAR`,
    ADD COLUMN `CCF_LEVEL` ENUM('A', 'B', 'C', 'OTHER') DEFAULT NULL COMMENT 'CCF等级' AFTER `AUTHOR_TEXT`;


INSERT INTO clouditera_aigc.AGENT (ID, AGENT_NAME, WORKFLOW_NAME, AGENT_TYPE, TAG, PROMPT, APP_ID, FLAG, SORT, SHORTCUT, KL_STATUS, `KEY`, CREATED_TIME, CREATED_BY, UPDATED_TIME, UPDATED_BY, MODE_TYPE, CONFIG, VERSION, STATUS, TYPE, COUNT_TOKENS, COMMON_HOME, COMMON_CONVERSATION, COMMON_QUESTION, PARENT_ID, AGENT_METADATA) VALUES ('26', '代码漏洞', '代码漏洞', 'COMMON', 'COMMON', null, '4012fbb5-bff5-4699-b6e4-6a74401becbc', 1, 26, 0, 0, 'app-SfX6YZY3y0JICiEP6bfQfhJU', null, null, '2025-10-30 11:05:55', '5b1076e0-a0bd-4ea5-ac86-ff73eddd630b', 'CHAT_WORKFLOW', '{"database":[],"llm":[]}', '1.0', 'AGENT_ALPHA', 'CODE', 1, 0, 0, 1, null, null);
INSERT INTO clouditera_aigc.AGENT (ID, AGENT_NAME, WORKFLOW_NAME, AGENT_TYPE, TAG, PROMPT, APP_ID, FLAG, SORT, SHORTCUT, KL_STATUS, `KEY`, CREATED_TIME, CREATED_BY, UPDATED_TIME, UPDATED_BY, MODE_TYPE, CONFIG, VERSION, STATUS, TYPE, COUNT_TOKENS, COMMON_HOME, COMMON_CONVERSATION, COMMON_QUESTION, PARENT_ID, AGENT_METADATA) VALUES ('27', '论文翻译', '论文翻译', 'COMMON', 'COMMON', null, '4012fbb5-bff5-4699-b6e4-6a74401becbc', 1, 26, 0, 0, 'app-SfX6YZY3y0JICiEP6bfQfhJU', null, null, '2025-10-30 11:05:55', '5b1076e0-a0bd-4ea5-ac86-ff73eddd630b', 'CHAT_WORKFLOW', '{"database":[],"llm":[]}', '1.0', 'AGENT_ALPHA', 'CODE', 1, 0, 0, 1, null, null);