server:
  port: 80
  servlet:
    context-path: ${CONTEXT_PATH}
springdoc:
  swagger-ui:
    enabled: ${SWAGGER_UI}
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB
  flyway:
    enabled: false
  security:
    oauth2:
      resource-server:
        jwt:
          # TODO:update ip
          issuer-uri: ${IAM_URL}/realms/Clouditera-IAM
          jwk-set-uri: ${spring.security.oauth2.resource-server.jwt.issuer-uri}/protocol/openid-connect/certs
# TODO:update ip
clouditera:
  dify:
    host: ${AI_BRAIN_HOST}
    compressedAppKey: app-8yeUYPPR06MA8nXpTdXgxFG0
    datasetsAppKey: dataset-JCxjL02kFmotViilJdoIB3mB
  cache:
    hostname: ${REDIS_HOST}
    port: ${REDIS_PORT}
    index: 2
    password: ${REDIS_PASSWOR}
  security:
    iamUrl: ${IAM_URL}
    realm: Clouditera-IAM
    clientId: clouditera-aigc
    clientSecret: jbSM7ihAH8i5AlYlUF5fLYn5BTJEs1B5
  oss:
    endpoint: ${MINIO_HOST}
    accessKey: ${MINIO_ROOT_USER}
    secretKey: ${MINIO_ROOT_PASSWORD}
  mysql:
    url: ${AIGC_MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_ROOT_PASSWORD}
  cncertmysql:
    url: ${CN_CERT_MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_ROOT_PASSWORD}
  sm2:
    privateKey: 6f866337bda6fd555033d5952dabe9fcc7c1d58e36294a8a391358c65f4cdf8a
    publicKey: 044f27668d4bdbb9607eeb679a14d23b4fa4e3aa02d63a2c2108a00f9c9cb290677e451eecf41f1f551cdbfbd678822fb54a915c2f38d1423e8db401a553e931ee
  filems:
    host: ${FILEMS_URL}
  collabnet:
    host: ${COLLABNET_HOST}
  task:
    image: rd.clouditera.com/sast/facade:${FACADE_IMAGE_VERSION}
    url: ${CN_CERT_MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_ROOT_PASSWORD}
