services:
  elasticsearch:
    image: rd.clouditera.com/sca-sast-lib/library/elasticsearch:8.12.2
    restart: always
    environment:
      ES_USER: ${ES_USER}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      ES_JAVA_OPTS: ${ES_JAVA_OPTS}
      xpack.security.enabled: true
      discovery.type: single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ${INSTALL_LOCAL}/es/data:/usr/share/elasticsearch/data
      - ${INSTALL_LOCAL}/es/plugins:/usr/share/elasticsearch/plugins
