services:
  client-http:
    image: rd.clouditera.com/aigc/client-http-api:v3.9.20
    restart: always
    environment:
      CONTEXT_PATH: /clientapi
      TZ: Asia/Shanghai
      SWAGGER_UI: false
    env_file:
      - .env
    volumes:
      - ./config/application.yml:/app/resources/application.yml
    ports:
      - "${CLIENT_HTTP_PORT}:80"
