services:
  elasticsearch:
    image: rd.clouditera.com/docker/elasticsearch:8.12.2
    restart: always
    environment:
      ES_USER: ${ES_USER}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      ES_JAVA_OPTS: ${ES_JAVA_OPTS}
      xpack.security.enabled: true
      discovery.type: single-node
    ports:
      - "${ELASTICSEARCH_HTTP_PORT:-10012}:9200"
      - "${ELASTICSEARCH_CLUSTER_PORT:-10013}:9300"
    volumes:
      - ${INSTALL_LOCAL}/es/data:/usr/share/elasticsearch/data
      - ${INSTALL_LOCAL}/es/plugins:/usr/share/elasticsearch/plugins
