services:
  storage:
    image: rd.clouditera.com/docker/minio:RELEASE.2023-08-16T20-17-30Z
    restart: always
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command:
      [
        'server',
        '/data',
        '--console-address',
        ':9001'
      ]
    ports:
      - "19000:9000"
      - "19001:9001"
    volumes:
      - ${INSTALL_LOCAL}/minioData:/data
