services:
  sast-http:
    image: rd.clouditera.com/aigc/wuji/sast-http-api:v5.2.34
    restart: always
    environment:
      CONTEXT_PATH: /sastapi
      TZ: Asia/Shanghai   # 设置时区为东八区
    ports:
      - "${SAST_HTTP_PORT}:80"
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/application.yml:/app/application.yml
      - ${INSTALL_LOCAL}/wuji/res:/tmp/sast/res
      - ${INSTALL_LOCAL}/wuji/code:/tmp/sast/code

  facade:
    profiles: ["facade"]
    image: rd.clouditera.com/sast/facade:v5.4.7
    ports:
      - "${SAST_HTTP_PORT}:80"
