version: '3'

services:
  node_manager:
    image: rd.clouditera.com/infra/collabnet:v2.7-node_manager-x86_64-test-8
    container_name: node_manager
    restart: always
    privileged: true
    # 使用host模式，不需要做端口映射
    network_mode: "host"
    environment:
      - DOCKER_MODE=true
      - SCHED_SERVER=192.168.31.26
      - FIRST_PARTY=true
      - CACHE_DIR=/cache
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./upgrade:/opt/node_manager/
      - ./config:/opt/config
      - ./cache:/cache
      - /var/lib/docker/volumes/:/var/lib/docker/volumes/
