services:
  mongo:
    image: rd.clouditera.com/docker/mongo:4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "${MONGO_PORT:-10014}:27017"
    volumes:
      - ${INSTALL_LOCAL}/mongod:/data/db
