version: '2'

services:
  playwright-service:
    image: rd.clouditera.com/firecrawl/firecrawl-playwright-service:v1.0.0
    environment:
      - PORT=3000
      - PROXY_SERVER=
      - PROXY_USERNAME=
      - PROXY_PASSWORD=
      - BLOCK_MEDIA=
    networks:
      - backend

  api:
    image: rd.clouditera.com/firecrawl/firecrawl-api:v1.0.0
    networks:
      - backend
    environment:
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - REDIS_RATE_LIMIT_URL=${REDIS_URL:-redis://redis:6379}
      - PLAYWRIGHT_MICROSERVICE_URL=${PLAYWRIGHT_MICROSERVICE_URL:-http://playwright-service:3000}
      - USE_DB_AUTHENTICATION=false
      - PORT=${PORT:-3002}
      - NUM_WORKERS_PER_QUEUE=
      - OPENAI_API_KEY=
      - OPENAI_BASE_URL=
      - MODEL_NAME=
      - SLACK_WEBHOOK_URL=
      - LLAMAPARSE_API_KEY=
      - LOGTAIL_KEY=
      - BULL_AUTH_KEY=
      - TEST_API_KEY=
      - POSTHOG_API_KEY=
      - POSTHOG_HOST=
      - SUPABASE_ANON_TOKEN=
      - SUPABASE_URL=
      - SUPABASE_SERVICE_TOKEN=
      - SCRAPING_BEE_API_KEY=
      - HOST=${HOST:-0.0.0.0}
      - SELF_HOSTED_WEBHOOK_URL=
      - LOGGING_LEVEL=
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis
      - playwright-service
    ports:
      - "3002:3002"
    command: [ "pnpm", "run", "start:production" ]

  worker:
    image: rd.clouditera.com/firecrawl/firecrawl-worker:v1.0.0
    networks:
      - backend
    environment:
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - REDIS_RATE_LIMIT_URL=${REDIS_URL:-redis://redis:6379}
      - PLAYWRIGHT_MICROSERVICE_URL=${PLAYWRIGHT_MICROSERVICE_URL:-http://playwright-service:3000}
      - USE_DB_AUTHENTICATION=false
      - PORT=${PORT:-3002}
      - NUM_WORKERS_PER_QUEUE=
      - OPENAI_API_KEY=
      - OPENAI_BASE_URL=
      - MODEL_NAME=
      - SLACK_WEBHOOK_URL=
      - LLAMAPARSE_API_KEY=
      - LOGTAIL_KEY=
      - BULL_AUTH_KEY=
      - TEST_API_KEY=
      - POSTHOG_API_KEY=
      - POSTHOG_HOST=
      - SUPABASE_ANON_TOKEN=
      - SUPABASE_URL=
      - SUPABASE_SERVICE_TOKEN=
      - SCRAPING_BEE_API_KEY=
      - HOST=${HOST:-0.0.0.0}
      - SELF_HOSTED_WEBHOOK_URL=
      - LOGGING_LEVEL=
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis
      - playwright-service
      - api
    command: [ "pnpm", "run", "workers" ]

  redis:
    image: rd.clouditera.com/docker/redis:7.2.0
    networks:
      - backend
    command: redis-server --bind 0.0.0.0

networks:
  backend:
    driver: bridge
