services:
  nacos:
    image: rd.clouditera.com/docker/nacos/nacos-server:v2.4.3
    container_name: nacos-standalone-mysql
    env_file:
      - .env
    ports:
      - "${NACOS_HTTP_PORT:-18848}:8848"
      - "${NACOS_GRPC_PORT:-19848}:9848"
    restart: always