services:
  rag_service_backend:
    image: rd.clouditera.com/aigc/rag/rag_service/backend:x86_64-0.6.1.post2
    ports:
      - "8081:8081"
    volumes:
      - ./data:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - POSTGRES_SERVER=rag_service_postgres
      - REDIS_SERVER=rag_service_redis
      - VECTOR_STORE_SERVER_HOST=rag_service_postgres
    env_file:
      - .env
    depends_on:
      - rag_service_postgres
      - rag_service_redis
    restart: always
  
  slow_parse_worker:
    image: rd.clouditera.com/aigc/rag/rag_service/backend:x86_64-0.6.1.post2
    volumes:
      - ./data:/app/data
    command: >
      celery -A backend.core.celery_app
      worker --loglevel=info
      --concurrency=1
      --pool=prefork
      --hostname=slow_parse_worker@%h
      --queues=document_slow_parse_queue
    env_file:
      - .env
    environment:
      - C_FORCE_ROOT=true
      - REDIS_SERVER=rag_service_redis
      - POSTGRES_SERVER=rag_service_postgres
      - VECTOR_STORE_SERVER_HOST=rag_service_postgres
    depends_on:
      - rag_service_postgres
      - rag_service_redis
    restart: always
       
  parse_worker:
    image: rd.clouditera.com/aigc/rag/rag_service/backend:x86_64-0.6.1.post2
    volumes:
      - ./data:/app/data
    command: >
      celery -A backend.core.celery_app
      worker --loglevel=info
      --concurrency=4
      --pool=prefork
      --hostname=parse_worker@%h
      --queues=document_parse_queue
    env_file:
      - .env
    environment:
      - C_FORCE_ROOT=true
      - REDIS_SERVER=rag_service_redis
      - POSTGRES_SERVER=rag_service_postgres
      - VECTOR_STORE_SERVER_HOST=rag_service_postgres
    depends_on:
      - rag_service_postgres
      - rag_service_redis
    restart: always
  
  vectorize_worker:
    image: rd.clouditera.com/aigc/rag/rag_service/backend:x86_64-0.6.1.post2
    volumes:
      - ./data:/app/data
    command: >
      celery -A backend.core.celery_app
      worker --loglevel=info
      --concurrency=4
      --pool=prefork
      --hostname=vectorize_worker@%h
      --queues=document_vectorize_queue
    env_file:
      - .env
    environment:
      - C_FORCE_ROOT=true
      - REDIS_SERVER=rag_service_redis
      - POSTGRES_SERVER=rag_service_postgres
      - VECTOR_STORE_SERVER_HOST=rag_service_postgres
    depends_on:
      - rag_service_postgres
      - rag_service_redis
    restart: always

  system_worker:
    image: rd.clouditera.com/aigc/rag/rag_service/backend:x86_64-0.6.1.post2
    volumes:
      - ./data:/app/data
    command: >
      celery -A backend.core.celery_app
      worker --loglevel=info
      --concurrency=4
      --pool=prefork
      --hostname=system_worker@%h
      --queues=system_task_queue
    env_file:
      - .env
    environment:
      - C_FORCE_ROOT=true
      - REDIS_SERVER=rag_service_redis
      - POSTGRES_SERVER=rag_service_postgres
      - VECTOR_STORE_SERVER_HOST=rag_service_postgres
    depends_on:
      - rag_service_postgres
      - rag_service_redis
    restart: always

  rag_service_flower:
    image: rd.clouditera.com/aigc/rag/rag_service/backend:x86_64-0.6.1.post2
    ports:
      - "35555:5555"
    command: >
      celery -A backend.core.celery_app flower
    env_file:
      - .env
    environment:
      - C_FORCE_ROOT=true
      - REDIS_SERVER=rag_service_redis
      - POSTGRES_SERVER=rag_service_postgres
      - VECTOR_STORE_SERVER_HOST=rag_service_postgres
    depends_on:
      - rag_service_postgres
      - rag_service_redis
    restart: always
  
  rag_service_frontend:
    image: rd.clouditera.com/aigc/rag/rag_service/frontend:x86_64-0.6.1.post2
    ports:
      - "8082:8080"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - rag_service_backend

  # 数据库服务
  rag_service_postgres:
    image: rd.clouditera.com/docker/vchord-postgres:pg17-v0.5.3
    ports:
      - "5432:5432"
    command: >
      postgres -c shared_preload_libraries=vchord -c max_connections=1000 -c shared_buffers=256MB -c effective_cache_size=1GB -c work_mem=4MB -c maintenance_work_mem=64MB
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: always

  rag_service_redis:
    image: rd.clouditera.com/docker/redis:8.0.2
    ports:
      - "6379:6379"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./redis-data:/data
      - ./redis.conf:/etc/redis/redis.conf
    command: redis-server /etc/redis/redis.conf
    restart: always

  rag_service_qdrant:
    image: rd.clouditera.com/docker/qdrant:v1.15
    ports:
      - "6333:6333"
      - "6334:6334"
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./qdrant-data:/qdrant/storage
    restart: always

  rag_service_etcd:
    image: quay.io/coreos/etcd:v3.5.18
    profiles:
      - milvus
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - ./milvus-data/etcd:/etcd
    command: etcd -advertise-client-urls=http://etcd:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3

  rag_service_minio:
    image: minio/minio:RELEASE.2024-12-18T13-15-44Z
    profiles:
      - milvus
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9001:9001"
      - "9000:9000"
    volumes:
      - ./milvus-data/minio:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  rag_service_milvus:
    image: milvusdb/milvus:v2.6.3
    profiles:
      - milvus
    command: ["milvus", "run", "standalone"]
    security_opt:
    - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: rag_service_etcd:2379
      MINIO_ADDRESS: rag_service_minio:9000
      MQ_TYPE: woodpecker
    volumes:
      - ./milvus-data/milvus:/var/lib/milvus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "rag_service_etcd"
      - "rag_service_minio"

  rag_service_chroma:
    image: chromadb/chroma:latest
    profiles:
      - chroma
    restart: always
    volumes:
      - ./chroma-data:/chroma_data
    ports:
      - "8000:8000"

# networks:
#   default:
#     external:
#       name: aigc
