
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

create database if not exists clouditera_aigc;

use clouditera_aigc;
-- clouditera_aigc.AGENT definition

CREATE TABLE `AGENT` (
  `ID` varchar(64) NOT NULL COMMENT '主键',
  `AGENT_NAME` varchar(64) DEFAULT NULL COMMENT '智能体名称',
  `WORKFLOW_NAME` varchar(64) DEFAULT NULL COMMENT '工作流名称',
  `AGENT_TYPE` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '智能体类型',
  `TAG` varchar(255) DEFAULT NULL,
  `PROMPT` varchar(255) DEFAULT NULL COMMENT '编排数据',
  `APP_ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '智能体ID',
  `FLAG` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否启用 1 为true , 0为flase。默认启用',
  `SORT` int DEFAULT NULL COMMENT '排序顺序',
  `SHORTCUT` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否增加快捷方式 1 为true , 0为flase。默认为false',
  `KL_STATUS` tinyint DEFAULT '0' COMMENT '是否可以上传文档0否，1是ture',
  `KEY` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT 'API_KEY',
  `CREATED_TIME` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `CREATED_BY` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '创建人',
  `UPDATED_TIME` timestamp NULL DEFAULT NULL COMMENT '最后一次时间',
  `UPDATED_BY` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '最后一次修改人',
  `MODE_TYPE` varchar(255) DEFAULT NULL COMMENT '应用类型',
  `CONFIG` text,
  `VERSION` varchar(255) DEFAULT NULL COMMENT '智能体版本',
  `STATUS` varchar(255) DEFAULT NULL COMMENT '智能体状态',
  `TYPE` varchar(100) DEFAULT NULL COMMENT '智能体分类',
  `COUNT_TOKENS` tinyint(1) DEFAULT '1' COMMENT '是否统计token',
  `COMMON_HOME` tinyint(1) NOT NULL DEFAULT '0' COMMENT '常用对话-首页 1为true，0为flase',
  `COMMON_CONVERSATION` tinyint(1) NOT NULL DEFAULT '0' COMMENT '常用对话-对话 1为true，0为flase',
  `COMMON_QUESTION` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否添加常用对话 1为true，0为flase，默认为true',
  `PARENT_ID` varchar(64) DEFAULT NULL COMMENT '父id',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- clouditera_aigc.AGENT_MODEL definition

CREATE TABLE `AGENT_MODEL` (
  `ID` varchar(64) NOT NULL COMMENT '主键',
  `USER_ID` varchar(255) DEFAULT NULL,
  `AGENT_ID` varchar(255) DEFAULT NULL COMMENT '模型提供商',
  `MODEL_ID` varchar(255) DEFAULT NULL COMMENT '智能体权限',
  `TYPE` varchar(255) DEFAULT NULL COMMENT '类型',
  `TEMPERATURE` float DEFAULT NULL COMMENT '温度',
  `TOP_P` int DEFAULT NULL COMMENT 'top_p',
  `MAX_TOKENS` int DEFAULT NULL COMMENT '最大返回值',
  `CREATED_TIME` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `CREATED_BY` varchar(64) DEFAULT NULL COMMENT '创建人',
  `UPDATED_TIME` timestamp NULL DEFAULT NULL COMMENT '最后一次时间',
  `UPDATED_BY` varchar(64) DEFAULT NULL COMMENT '最后一次修改人',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- clouditera_aigc.AGENT_SHORTCUT definition

CREATE TABLE `AGENT_SHORTCUT` (
  `ID` varchar(255) NOT NULL COMMENT '主键',
  `AGENT_ID` varchar(64) DEFAULT NULL COMMENT 'AGENTID',
  `SORT` int DEFAULT NULL COMMENT '排序',
  `CREATED_TIME` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `CREATED_BY` varchar(64) DEFAULT NULL COMMENT '创建人',
  `UPDATED_TIME` timestamp NULL DEFAULT NULL COMMENT '最后一次时间',
  `UPDATED_BY` varchar(64) DEFAULT NULL COMMENT '最后一次修改人',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- clouditera_aigc.ASSET_JUDGMENT_TAG definition

CREATE TABLE `ASSET_JUDGMENT_TAG` (
  `ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '主键ID',
  `NAME` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '标签名称',
  `CREATED_TIME` datetime(6) DEFAULT NULL COMMENT '创建时间',
  `CREATED_BY` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '创建人',
  `UPDATED_TIME` datetime(6) DEFAULT NULL COMMENT '更新时间',
  `UPDATED_BY` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '更新人'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='资产研判标签表';


-- clouditera_aigc.ASSET_JUDGMENT_TAG_REL definition

CREATE TABLE `ASSET_JUDGMENT_TAG_REL` (
  `ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '主键ID',
  `TARGET_ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '研判任务ID',
  `TAG_ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '标签ID',
  `CREATED_TIME` datetime(6) DEFAULT NULL COMMENT '创建时间',
  `CREATED_BY` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '创建人',
  `UPDATED_TIME` datetime(6) DEFAULT NULL COMMENT '更新时间',
  `UPDATED_BY` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='安全资讯标签关联表';


-- clouditera_aigc.ASSET_JUDGMENT_TARGET definition

CREATE TABLE `ASSET_JUDGMENT_TARGET` (
  `ID` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '主键ID',
  `TASK_ID` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '任务ID',
  `ADDRESS` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '研判地址',
  `CORRELATION` tinyint DEFAULT NULL COMMENT '相关性',
  `SUMMARY` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '概述',
  `CONFIDENCE_DEGREE` double DEFAULT NULL COMMENT '置信度',
  `ACCORDING` text COLLATE utf8mb4_unicode_ci COMMENT '依据',
  `ANALYZE_CONTENT` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '研判全文',
  `ERROR_MESSAGE` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '错误信息',
  `CREATED_TIME` timestamp(6) NULL DEFAULT NULL COMMENT '创建时间',
  `CREATED_BY` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '创建人',
  `UPDATED_TIME` timestamp(6) NULL DEFAULT NULL COMMENT '更新时间',
  `UPDATED_BY` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='资产研判目标';


-- clouditera_aigc.ASSET_JUDGMENT_TASK definition

CREATE TABLE `ASSET_JUDGMENT_TASK` (
  `ID` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '主键ID',
  `NAME` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '任务名称',
  `INPUT_TYPE` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '输入类型： 文本、文件',
  `STATUS` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '任务状态',
  `REPORT_NAME` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '报告名称',
  `REPORT_STATUS` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '报告生成状态',
  `REPORT_UPDATED_TIME` timestamp(6) NULL DEFAULT NULL COMMENT '报告创建时间',
  `FILE_ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '文件ID',
  `ERROR_MESSAGE` text COLLATE utf8mb4_unicode_ci COMMENT '任务失败原因',
  `REPORT_ERROR_MESSAGE` text COLLATE utf8mb4_unicode_ci COMMENT '报告生成失败原因',
  `WORKFLOW_TASK_ID` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '工作流任务ID',
  `CREATED_TIME` timestamp(6) NULL DEFAULT NULL COMMENT '创建时间',
  `CREATED_BY` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '创建人',
  `UPDATED_TIME` timestamp(6) NULL DEFAULT NULL COMMENT '更新时间',
  `UPDATED_BY` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='资产研判任务表';


-- clouditera_aigc.ATTACK_SUMMARY definition

CREATE TABLE `ATTACK_SUMMARY` (
  `FILE_ID` varchar(255) NOT NULL,
  `CONTENT` text,
  `RATING` varchar(255) DEFAULT NULL,
  `STATUS` varchar(255) DEFAULT NULL,
  `CREATED_TIME` datetime(6) DEFAULT NULL,
  `CREATED_BY` varchar(255) DEFAULT NULL,
  `UPDATED_TIME` datetime(6) DEFAULT NULL,
  `UPDATED_BY` varchar(255) DEFAULT NULL,
  `TOTAL_DATA` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  PRIMARY KEY (`FILE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- clouditera_aigc.CHECK_ISSUE definition

CREATE TABLE `CHECK_ISSUE` (
  `ID` varchar(64) NOT NULL COMMENT '主键',
  `HIS_ID` varchar(64) NOT NULL COMMENT '历史id',
  `POCDATA` varchar(225) DEFAULT NULL COMMENT 'POC信息',
  `CHACKCONTENT` text COMMENT 'AI对话生成的内容',
  `STATUS` varchar(225) DEFAULT NULL COMMENT '状态',
  `CREATED_TIME` datetime(6) DEFAULT NULL COMMENT '创建时间',
  `CREATED_BY` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '创建人',
  `UPDATED_TIME` datetime(6) DEFAULT NULL COMMENT '更新时间',
  `UPDATED_BY` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='漏洞排查';


-- clouditera_aigc.COMMON_QUESTION definition

CREATE TABLE `COMMON_QUESTION` (
  `ID` varchar(64) NOT NULL COMMENT '主键',
  `AGENT_ID` varchar(64) DEFAULT NULL COMMENT 'agentId',
  `GROUP_COMMON_QUESTION_ID` varchar(64) DEFAULT NULL COMMENT '组ID',
  `QUESTION` text COMMENT '常见问题',
  `STATUS` tinyint DEFAULT '0' COMMENT '0为禁用,1为启用',
  `CREATED_TIME` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `CREATED_BY` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '创建人',
  `UPDATED_TIME` timestamp NULL DEFAULT NULL COMMENT '最后一次时间',
  `UPDATED_BY` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '最后一次修改人',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- clouditera_aigc.COMMON_SEARCH definition

CREATE TABLE `COMMON_SEARCH` (
  `ID` varchar(64) NOT NULL COMMENT '主键',
  `AGENT_TYPE` varchar(255) DEFAULT NULL,
  `CONTENT` text,
  `CREATED_TIME` datetime(6) DEFAULT NULL,
  `CREATED_BY` varchar(255) DEFAULT NULL,
  `UPDATED_TIME` datetime(6) DEFAULT NULL,
  `UPDATED_BY` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- clouditera_aigc.CONVERSATION_FILE definition

CREATE TABLE `CONVERSATION_FILE` (
  `ID` varchar(64) NOT NULL,
  `FILE_ID` varchar(64) DEFAULT NULL,
  `FILE_DETAIL_ID` varchar(64) DEFAULT NULL,
  `CONVERSATION_ID` varchar(255) DEFAULT NULL,
  `VUL_ID` varchar(64) DEFAULT NULL COMMENT '缺陷ID',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- clouditera_aigc.CONVERSATION_WORKFLOW definition

CREATE TABLE `CONVERSATION_WORKFLOW` (
  `CONVERSATION_ID` varchar(64) NOT NULL,
  `WORKFLOW_ID` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`CONVERSATION_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- clouditera_aigc.CTF definition

CREATE TABLE `CTF` (
  `ID` varchar(64) NOT NULL,
  `CONVERSATION_ID` varchar(64) DEFAULT NULL,
  `CONTEXT` text,
  `CREATED_TIME` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `CREATED_BY` varchar(64) DEFAULT NULL COMMENT '创建人',
  `UPDATED_TIME` timestamp NULL DEFAULT NULL COMMENT '最后一次时间',
  `UPDATED_BY` varchar(64) DEFAULT NULL COMMENT '最后一次修改人',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- clouditera_aigc.CTF_TOPIC definition

CREATE TABLE `CTF_TOPIC` (
  `ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT 'ID',
  `NAME` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '名称',
  `TYPE` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '类型',
  `CONVERSATION_ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '会话ID',
  `FILE_ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '文件ID',
  `CREATED_TIME` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `CREATED_BY` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '创建人',
  `UPDATED_TIME` timestamp NULL DEFAULT NULL COMMENT '最后一次时间',
  `UPDATED_BY` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '最后一次修改人',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- clouditera_aigc.DATASETS definition

CREATE TABLE `DATASETS` (
  `ID` varchar(36) NOT NULL COMMENT '主键',
  `AGENT_ID` varchar(64) DEFAULT NULL COMMENT 'AgentId',
  `DATASETS_ID` varchar(64) DEFAULT NULL COMMENT '记忆空间知识库ID',
  `NAME` varchar(64) DEFAULT NULL COMMENT '知识库名称',
  `STATUS` tinyint DEFAULT '1' COMMENT '是否可以上传文档0否，1是ture',
  `ALL` tinyint DEFAULT '0' COMMENT '是否传入全部知识库，0不传如，1穿入',
  `SHOW` tinyint DEFAULT '1' COMMENT '是否展示0，不展示，1展示',
  `CREATED_TIME` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `CREATED_BY` varchar(64) DEFAULT NULL COMMENT '创建人',
  `UPDATED_TIME` timestamp NULL DEFAULT NULL COMMENT '最后一次时间',
  `UPDATED_BY` varchar(64) DEFAULT NULL COMMENT '最后一次修改人',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- clouditera_aigc.DATASETS_DOCUMENTS definition

CREATE TABLE `DATASETS_DOCUMENTS` (
  `ID` varchar(36) NOT NULL COMMENT '主键',
  `AGENT_ID` varchar(64) DEFAULT NULL COMMENT 'AgentId',
  `DATASETS_ID` varchar(64) DEFAULT NULL COMMENT '记忆空间知识库ID',
  `DOCUMENT_ID` varchar(64) DEFAULT NULL COMMENT '文档ID',
  `NAME` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '名称',
  `GROUP_ID` varchar(64) DEFAULT NULL COMMENT '组织ID',
  `CREATED_TIME` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `CREATED_BY` varchar(64) DEFAULT NULL COMMENT '创建人',
  `UPDATED_TIME` timestamp NULL DEFAULT NULL COMMENT '最后一次时间',
  `UPDATED_BY` varchar(64) DEFAULT NULL COMMENT '最后一次修改人',
  `BATCH` varchar(255) DEFAULT NULL COMMENT '批次号',
  `STATUS` varchar(255) DEFAULT NULL COMMENT '状态',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- clouditera_aigc.DEFECT_ANALYSIS_CLASSIFY definition

CREATE TABLE `DEFECT_ANALYSIS_CLASSIFY` (
  `ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'ID',
  `TASK_ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '任务id',
  `DEFECT_TYPE` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '缺陷类型',
  `SEVERITY` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '缺陷等级',
  `DETAIL_INFO` text COLLATE utf8mb4_unicode_ci COMMENT '详细信息',
  `FIX_SUGGEST` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '修复建议',
  `DEFECT_DESCRIBE` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '缺陷描述',
  `CAUSE_ANALYSIS` text COLLATE utf8mb4_unicode_ci COMMENT '成因分析',
  `CREATED_BY` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '创建人',
  `CREATED_TIME` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `UPDATED_BY` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '最后一次修改人',
  `UPDATED_TIME` timestamp NULL DEFAULT NULL COMMENT '最后一次时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='缺陷分析-缺陷分类表';


-- clouditera_aigc.DEFECT_ANALYSIS_CONCURRENCY definition

CREATE TABLE `DEFECT_ANALYSIS_CONCURRENCY` (
  `ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '主键ID',
  `GROUP_ID` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '组id',
  `CONCURRENCY` int DEFAULT NULL COMMENT '并发数',
  `CREATED_BY` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '创建人',
  `CREATED_TIME` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `UPDATED_BY` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '最后一次修改人',
  `UPDATED_TIME` timestamp NULL DEFAULT NULL COMMENT '最后一次时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='缺陷分析-并发设置表';


-- clouditera_aigc.DEFECT_ANALYSIS_INFO definition

CREATE TABLE `DEFECT_ANALYSIS_INFO` (
  `ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'ID',
  `CLASSIFY_ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '分类id',
  `AI_SAST_TASK_ID` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'sast任务id',
  `CODE_PATH` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '代码文件路径',
  `BURST_ROW_NUMBER` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '爆发行号',
  `BURST_ROW_CODE` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '爆发行代码',
  `TRACK_PATH` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '跟踪路径',
  `JUDGE_RESULT` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '研判结果',
  `CAUSE_ANALYSIS` text COLLATE utf8mb4_unicode_ci COMMENT '成因分析',
  `FIX_SUGGEST` text COLLATE utf8mb4_unicode_ci COMMENT '修复建议',
  `CREATED_BY` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '创建人',
  `CREATED_TIME` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `UPDATED_BY` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '最后一次修改人',
  `UPDATED_TIME` timestamp NULL DEFAULT NULL COMMENT '最后一次时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='缺陷分析-缺陷信息表';


-- clouditera_aigc.DEFECT_ANALYSIS_TASK definition

CREATE TABLE `DEFECT_ANALYSIS_TASK` (
  `ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '主键ID',
  `TASK_NAME` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '任务名称',
  `CODE_FILE_NAME` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '工程文件名',
  `TASK_NODE` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '任务节点',
  `TASK_STATUS` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '任务状态',
  `FAILURE_REASON` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '失败原因',
  `AUDIT_FILE_STATUS` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '审计报告状态',
  `PROJECT_ID` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT 'AiSast项目id',
  `MANUFACTURER` varchar(32) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '厂商',
  `UPLOAD_TIME` timestamp NULL DEFAULT NULL COMMENT '上传时间',
  `CREATED_BY` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '创建人',
  `CREATED_TIME` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `UPDATED_BY` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '最后一次修改人',
  `UPDATED_TIME` timestamp NULL DEFAULT NULL COMMENT '最后一次时间',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='缺陷分析-研判任务表';


-- clouditera_aigc.DOCUMENT_JOB definition

CREATE TABLE `DOCUMENT_JOB` (
  `ID` varchar(64) NOT NULL COMMENT '主键',
  `FILE_ID` varchar(64) DEFAULT NULL COMMENT '文件ID',
  `DATASETS_ID` varchar(255) DEFAULT NULL COMMENT 'DATASETS',
  `AGENT_ID` varchar(255) DEFAULT NULL COMMENT 'agent ID ',
  `DOCUMENT_ID` varchar(255) DEFAULT NULL COMMENT 'documentsId',
  `DOCUMENT_NAME` varchar(255) DEFAULT NULL COMMENT 'documentsName',
  `PARSE_TEXT` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `CONTEXT` longtext COMMENT '文件内容',
  `STATUS` varchar(64) DEFAULT NULL,
  `ERROR_LOG` varchar(255) DEFAULT NULL COMMENT '错误日志',
  `THREAD_ID` varchar(255) DEFAULT NULL,
  `BATCH` varchar(64) DEFAULT NULL,
  `CREATED_TIME` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `CREATED_BY` varchar(64) DEFAULT NULL COMMENT '创建人',
  `UPDATED_TIME` timestamp NULL DEFAULT NULL COMMENT '最后一次时间',
  `UPDATED_BY` varchar(64) DEFAULT NULL COMMENT '最后一次修改人',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- clouditera_aigc.DOCUMENT_METADATA definition

CREATE TABLE `DOCUMENT_METADATA` (
  `id` int NOT NULL AUTO_INCREMENT COMMENT '主键',
  `file_name` varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '原始文件名',
  `file_ext` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '文件后缀',
  `file_size` bigint NOT NULL COMMENT '文件大小',
  `file_md5` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '文件MD5值',
  `file_created_time` datetime NOT NULL COMMENT '文件创建时间，stat命令能看到',
  `file_modified_time` datetime NOT NULL COMMENT '文件修改时间，stat命令能看到',
  `source_type` enum('local','web','api','upload') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'local' COMMENT '文档来源',
  `source_url` varchar(2000) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '文档来源链接',
  `storage_path` varchar(1000) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '文件存储位置',
  `parse_time` datetime NOT NULL COMMENT '文档收录时间，就是开始解析的时间',
  `parsed_content` longtext COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '解析后的文件内容',
  `original_title` varchar(500) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '文档标题',
  `summary_content` text COLLATE utf8mb4_unicode_ci COMMENT '文档摘要',
  `keywords` json DEFAULT NULL COMMENT '关键词',
  `ai_notes` longtext COLLATE utf8mb4_unicode_ci COMMENT 'AI生成的文档笔记',
  `ai_toc` text COLLATE utf8mb4_unicode_ci COMMENT 'AI提取的文档目录',
  `ai_recommended_qa` json DEFAULT NULL COMMENT 'AI推荐的问答对',
  `created_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `updated_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_file_name` (`file_name`),
  KEY `idx_file_md5` (`file_md5`),
  KEY `idx_parse_time` (`parse_time`),
  KEY `idx_source_type` (`source_type`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='文档元数据表';


-- clouditera_aigc.FILE definition

CREATE TABLE `FILE` (
  `ID` varchar(64) NOT NULL,
  `FILE_PATH` text,
  `FILE_NAME` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `BUCKET_NAME` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `DATASETS_ID` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'DATASETS',
  `AGENT_ID` varchar(255) DEFAULT NULL COMMENT 'agent ID ',
  `DOCUMENT_ID` varchar(255) DEFAULT NULL COMMENT 'documentsId',
  `DOCUMENT_NAME` varchar(255) DEFAULT NULL COMMENT 'documentsName',
  `CONTEXT` longtext COMMENT '文件内容',
  `USER_ID` varchar(64) DEFAULT NULL,
  `CONVERSATION_ID` varchar(64) DEFAULT NULL,
  `CREATED_TIME` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `CREATED_BY` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '创建人',
  `UPDATED_TIME` timestamp NULL DEFAULT NULL COMMENT '最后一次时间',
  `UPDATED_BY` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '最后一次修改人',
  `REPO_ID` varchar(64) DEFAULT NULL COMMENT '代码仓库ID',
  `ORIGINAL_FILE_NAME` varchar(64) DEFAULT NULL COMMENT '原始文件名称',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- clouditera_aigc.FILE_AGENT_SPECIFICATION definition

CREATE TABLE `FILE_AGENT_SPECIFICATION` (
  `ID` varchar(64) NOT NULL,
  `FILE_PATH` varchar(255) DEFAULT NULL,
  `FILE_NAME` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `AGENT_ID` varchar(255) DEFAULT NULL COMMENT 'agent ID ',
  `BUCKET_NAME` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `CREATED_TIME` datetime(6) DEFAULT NULL,
  `CREATED_BY` varchar(255) DEFAULT NULL,
  `UPDATED_TIME` datetime(6) DEFAULT NULL,
  `UPDATED_BY` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- clouditera_aigc.FILE_DETAIL definition

CREATE TABLE `FILE_DETAIL` (
  `ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `FILE_ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `PATH` text,
  `LANGUAGE` varchar(255) DEFAULT NULL,
  `CREATED_TIME` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `CREATED_BY` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '创建人',
  `UPDATED_TIME` timestamp NULL DEFAULT NULL COMMENT '最后一次时间',
  `UPDATED_BY` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '最后一次修改人',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- clouditera_aigc.FILE_FIXED definition

CREATE TABLE `FILE_FIXED` (
  `ID` varchar(64) NOT NULL,
  `FILE_DETAIL_ID` varchar(64) DEFAULT NULL,
  `FIX_CONTENT` longtext,
  `CREATED_TIME` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `CREATED_BY` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '创建人',
  `UPDATED_TIME` timestamp NULL DEFAULT NULL COMMENT '最后一次时间',
  `UPDATED_BY` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '最后一次修改人',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- clouditera_aigc.GROUP_COMMON_QUESTION definition

CREATE TABLE `GROUP_COMMON_QUESTION` (
  `ID` varchar(64) NOT NULL COMMENT '主键',
  `AGENT_ID` varchar(64) DEFAULT NULL COMMENT 'agentId',
  `GROUP_ID` varchar(255) DEFAULT NULL COMMENT '组ID',
  `QUESTION` text COMMENT '常见问题',
  `CREATED_TIME` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `CREATED_BY` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '创建人',
  `UPDATED_TIME` timestamp NULL DEFAULT NULL COMMENT '最后一次时间',
  `UPDATED_BY` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '最后一次修改人',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- clouditera_aigc.HISTORY_ISSUE definition

CREATE TABLE `HISTORY_ISSUE` (
  `ID` varchar(64) NOT NULL COMMENT '主键',
  `AGENT_TYPE` varchar(255) DEFAULT NULL,
  `QUERY_NAME` text,
  `ISSUE_TYPE` varchar(255) DEFAULT NULL,
  `CONVERSATION_ID` varchar(255) DEFAULT NULL,
  `RATING` varchar(255) DEFAULT NULL COMMENT '点赞点踩',
  `STATUS` varchar(255) DEFAULT NULL,
  `SUMMARY` longtext,
  `CONTENT` longtext,
  `TITLE_CN` longtext COMMENT '中文标题',
  `CREATED_TIME` datetime(6) DEFAULT NULL,
  `CREATED_BY` varchar(255) DEFAULT NULL,
  `UPDATED_TIME` datetime(6) DEFAULT NULL,
  `UPDATED_BY` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='历史检索';


-- clouditera_aigc.HOT_ISSUE definition

CREATE TABLE `HOT_ISSUE` (
  `ID` varchar(64) NOT NULL COMMENT '主键',
  `AGENT_TYPE` varchar(255) DEFAULT NULL,
  `CONTENT` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `TYPE` varchar(255) DEFAULT NULL COMMENT '类型',
  `SOURCE_CONTENT` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci,
  `URL` varchar(255) DEFAULT NULL,
  `SOURCE_ID` varchar(255) DEFAULT NULL,
  `ARTICLE_TITLE` varchar(255) DEFAULT NULL COMMENT '文章标题',
  `PUBLISH_TIME` varchar(255) DEFAULT NULL COMMENT '发布时间',
  `STATUS` varchar(255) DEFAULT NULL COMMENT '状态',
  `CREATED_TIME` datetime(6) DEFAULT NULL,
  `CREATED_BY` varchar(255) DEFAULT NULL,
  `UPDATED_TIME` datetime(6) DEFAULT NULL,
  `UPDATED_BY` varchar(255) DEFAULT NULL,
  `PIC` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '缩略图',
  `SOURCE_TYPE` varchar(100) DEFAULT NULL COMMENT '数据源类型',
  `NEXT_RETRY_TIME` datetime(6) DEFAULT NULL COMMENT '下次重试时间',
  `RETRY_COUNT` int DEFAULT NULL COMMENT '重试次数',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='热点事件';


-- clouditera_aigc.INVITATION_CODE definition

CREATE TABLE `INVITATION_CODE` (
  `ID` varchar(64) NOT NULL COMMENT '主键',
  `CODE` varchar(6) DEFAULT NULL COMMENT '邀请码',
  `CODE_INFO` text COMMENT '邀请码详情',
  `EXPIRED` timestamp NULL DEFAULT NULL COMMENT '过期时间',
  `PERSON_KNOWLEDGE_COUNT` int DEFAULT NULL COMMENT '个人知识库数量',
  `GROUP_KNOWLEDGE_COUNT` int DEFAULT NULL COMMENT '团队知识库数量',
  `DOCUMENT_COUNT` int DEFAULT NULL COMMENT '知识库内文档数量',
  `CREATED_TIME` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `CREATED_BY` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '创建人',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='邀请码';


-- clouditera_aigc.INVITATION_CODE_GROUP definition

CREATE TABLE `INVITATION_CODE_GROUP` (
  `ID` varchar(64) NOT NULL COMMENT '主键',
  `CODE_ID` varchar(64) DEFAULT NULL COMMENT '邀请码ID',
  `CODE` varchar(6) DEFAULT NULL COMMENT '邀请码',
  `GROUP_ID` varchar(64) NOT NULL COMMENT '邀请码详情',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='邀请码绑定组织';


-- clouditera_aigc.KNOWLEDGE_BASE definition

CREATE TABLE `KNOWLEDGE_BASE` (
  `ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '主键ID',
  `AGENT_ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'AgentId',
  `NAME` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '知识库名称',
  `DESCRIPTION` text COLLATE utf8mb4_unicode_ci COMMENT '描述',
  `DOCUMENT_COUNT` int DEFAULT NULL COMMENT '文档数量',
  `TYPE` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '类型：PERSON，GROUP，SYSTEM',
  `STATUS` tinyint DEFAULT NULL COMMENT '0-未公开，1-公开',
  `GROUP_ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '组ID',
  `INDUSTRY_ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '行业类型ID',
  `DOC_UPLOAD_TIME` timestamp NULL DEFAULT NULL COMMENT '文档最后上传时间',
  `CREATED_TIME` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `CREATED_BY` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '创建人',
  `UPDATED_TIME` timestamp NULL DEFAULT NULL COMMENT '最后一次时间',
  `UPDATED_BY` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '最后一次修改人',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='安全智库-知识库';


-- clouditera_aigc.KNOWLEDGE_BASE_HISTORY definition

CREATE TABLE `KNOWLEDGE_BASE_HISTORY` (
  `ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '主键ID',
  `AGENT_ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'AgentId',
  `USER_ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '用户ID',
  `CONVERSATION_ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '对话ID',
  `KNOWLEDGE_BASE_ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '知识库ID',
  `TYPE` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '类型：PERSON，GROUP，SYSTEM',
  `NAME` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '内容',
  `CREATED_TIME` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `CREATED_BY` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '创建人',
  `UPDATED_TIME` timestamp NULL DEFAULT NULL COMMENT '最后一次时间',
  `UPDATED_BY` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '最后一次修改人',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='安全智库-历史记录';


-- clouditera_aigc.KNOWLEDGE_BASE_TYPE definition

CREATE TABLE `KNOWLEDGE_BASE_TYPE` (
  `ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '主键ID',
  `NAME` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '名称',
  `SORT` int DEFAULT NULL COMMENT '排序',
  `CREATED_TIME` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `CREATED_BY` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '创建人',
  `UPDATED_TIME` timestamp NULL DEFAULT NULL COMMENT '最后一次时间',
  `UPDATED_BY` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '最后一次修改人',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='安全智库-行业类型表';


-- clouditera_aigc.KNOWLEDGE_BASE_USER_REL definition

CREATE TABLE `KNOWLEDGE_BASE_USER_REL` (
  `ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '主键ID',
  `USER_ID` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '用户ID',
  `KNOWLEDGE_BASE_ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '知识库ID',
  `TYPE` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '类型：PERSON，GROUP，SYSTEM',
  `CREATED_TIME` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `CREATED_BY` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '创建人',
  `UPDATED_TIME` timestamp NULL DEFAULT NULL COMMENT '最后一次时间',
  `UPDATED_BY` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '最后一次修改人',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='安全智库-用户关联表';


-- clouditera_aigc.KNOWLEDGE_CATALOG definition

CREATE TABLE `KNOWLEDGE_CATALOG` (
  `ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '知识库目录ID',
  `NAME` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '类别名称',
  `PARENT_ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '父ID',
  `LEVEL` int DEFAULT NULL COMMENT '等级',
  `SORT_INDEX` int DEFAULT NULL COMMENT '排序',
  `TYPE` varchar(255) DEFAULT NULL,
  `COMPILE_FLAG` bit(1) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- clouditera_aigc.KNOWLEDGE_INFORMATION definition

CREATE TABLE `KNOWLEDGE_INFORMATION` (
  `ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '主键',
  `CATALOG_ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '所属分类',
  `BUG_NO` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'BUG类型编号',
  `PARENT_BUG_NO` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'BUG类型父级编号',
  `BUG_NAME` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'BUG名称',
  `BUG_NAME_EN` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'BUG类型名',
  `BUG_SIGN` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT 'BUG类型号',
  `BUG_LEVEL` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'BUG级别',
  `CODE_LANGUAGE` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '所属语言',
  `DESCRIPTION` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '描述',
  `FREQUENT_RESULT_KEYWORD` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '常见后果关键词',
  `FREQUENT_RESULT` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '常见后果',
  `REPAIR_OPINION` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '修复意见',
  `EXAMPLE` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '示例',
  `ERROR_EXAMPLE` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '错误示例',
  `CREATED_TIME` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `CREATED_BY` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '创建人',
  `UPDATED_TIME` timestamp NULL DEFAULT NULL COMMENT '最后一次时间',
  `UPDATED_BY` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '最后一次修改',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `BUG_SIGN` (`BUG_SIGN`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- clouditera_aigc.MESSAGE_RETRIEVER definition

CREATE TABLE `MESSAGE_RETRIEVER` (
  `MESSAGE_ID` varchar(64) NOT NULL,
  `MESSAGE_END` longtext,
  PRIMARY KEY (`MESSAGE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- clouditera_aigc.MODEL definition

CREATE TABLE `MODEL` (
  `ID` varchar(64) NOT NULL COMMENT '主键',
  `GROUP_ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '组id',
  `MODEL_NAME` varchar(255) DEFAULT NULL COMMENT '模型名称',
  `MODEL_TYPE` varchar(255) DEFAULT NULL COMMENT '类型类型',
  `PROVIDER` varchar(255) DEFAULT NULL COMMENT '模型提供商',
  `AGENT_IDS` json DEFAULT NULL COMMENT '智能体权限',
  `TYPE` varchar(255) DEFAULT NULL COMMENT '类型',
  `TEMPERATURE` float DEFAULT NULL COMMENT '温度',
  `TOP_P` int DEFAULT NULL COMMENT 'top_p',
  `MAX_TOKENS` int DEFAULT NULL COMMENT '最大返回值',
  `ACTIVE` tinyint DEFAULT '0' COMMENT '默认激活',
  `CONTEXT_SIZE` varchar(32) DEFAULT NULL COMMENT '模型上下文长度',
  `STATUS` tinyint(1) DEFAULT '0' COMMENT '模型状态：1-在线，0-不在线',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- clouditera_aigc.NUCLEI_ASSET definition

CREATE TABLE `NUCLEI_ASSET` (
  `ID` varchar(64) NOT NULL COMMENT '主键',
  `HISTORY_ID` varchar(64) DEFAULT NULL COMMENT '历史表ID',
  `CVE_ID` varchar(64) DEFAULT NULL COMMENT 'CVE ID',
  `YQ_ID` varchar(64) DEFAULT NULL COMMENT 'YQ ID',
  `NAME` varchar(255) DEFAULT NULL COMMENT '资产名称',
  `IP` varchar(64) DEFAULT NULL COMMENT '资产地址',
  `STATUS` varchar(64) DEFAULT NULL COMMENT '状态',
  `SUMMARY` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '总结',
  `CREATED_TIME` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `CREATED_BY` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '创建人',
  `UPDATED_TIME` timestamp NULL DEFAULT NULL COMMENT '最后一次时间',
  `UPDATED_BY` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '最后一次修改人',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- clouditera_aigc.PENETRATION_STRATEGY_TOOL definition

CREATE TABLE `PENETRATION_STRATEGY_TOOL` (
  `ID` varchar(64) NOT NULL COMMENT '主键',
  `NAME` varchar(64) DEFAULT NULL COMMENT '名称',
  `TOOL` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `DESCRIPTION` text COMMENT '描述',
  `CREATED_TIME` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `CREATED_BY` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '创建人',
  `UPDATED_TIME` timestamp NULL DEFAULT NULL COMMENT '最后一次时间',
  `UPDATED_BY` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '最后一次修改人',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- clouditera_aigc.PENETRATION_TOOLS_FILE definition

CREATE TABLE `PENETRATION_TOOLS_FILE` (
  `ID` varchar(64) NOT NULL,
  `FILE_NAME` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `BUCKET_NAME` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `CONVERSATION_ID` varchar(64) DEFAULT NULL,
  `CREATED_TIME` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `CREATED_BY` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '创建人',
  `UPDATED_TIME` timestamp NULL DEFAULT NULL COMMENT '最后一次时间',
  `UPDATED_BY` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '最后一次修改人',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- clouditera_aigc.PHISHING_EMAIL definition

CREATE TABLE `PHISHING_EMAIL` (
  `ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '主键',
  `CONVERSATION_ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '用户ID',
  `NAME` varchar(255) DEFAULT NULL COMMENT '列表名称',
  `EMAIL_THEME` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT ' 邮箱主题',
  `TYPE` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '钓鱼类型',
  `SENDER` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '发件人',
  `ADDRESSEE` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '收件人',
  `CONTENT` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '邮件内容',
  `CREATED_TIME` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `CREATED_BY` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '创建人',
  `UPDATED_TIME` timestamp NULL DEFAULT NULL COMMENT '最后一次时间',
  `UPDATED_BY` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '最后一次修改人',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- clouditera_aigc.PHISHING_EMAIL_CONFIG definition

CREATE TABLE `PHISHING_EMAIL_CONFIG` (
  `ID` varchar(64) NOT NULL COMMENT '主键',
  `AGENT_ID` varchar(64) DEFAULT NULL COMMENT 'agent Id',
  `TYPE` varchar(255) DEFAULT NULL COMMENT '钓鱼邮件类型',
  `CREATED_TIME` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `CREATED_BY` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '创建人',
  `UPDATED_TIME` timestamp NULL DEFAULT NULL COMMENT '最后一次时间',
  `UPDATED_BY` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '最后一次修改人',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- clouditera_aigc.QUERY definition

CREATE TABLE `QUERY` (
  `ID` varchar(64) NOT NULL,
  `QUERY` text COMMENT '问题',
  `AHENT_ID` varchar(64) DEFAULT NULL,
  `CREATED_TIME` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `CREATED_BY` varchar(64) DEFAULT NULL COMMENT '创建人',
  `UPDATED_TIME` timestamp NULL DEFAULT NULL COMMENT '最后一次时间',
  `UPDATED_BY` varchar(64) DEFAULT NULL COMMENT '最后一次修改人',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- clouditera_aigc.RECOMMEND definition

CREATE TABLE `RECOMMEND` (
  `ID` varchar(64) NOT NULL,
  `CONTEXT` varchar(255) DEFAULT NULL,
  `TYPE` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- clouditera_aigc.REPORT_DETAIL definition

CREATE TABLE `REPORT_DETAIL` (
  `ID` varchar(64) DEFAULT NULL,
  `REPORT_NAME` varchar(255) DEFAULT NULL,
  `REPORT_DATE` datetime(6) DEFAULT NULL,
  `REPORT_PATH` longtext,
  `TASK_ID` longtext,
  `REPORT_STATUS` longtext,
  `CREATED_TIME` datetime(6) DEFAULT NULL,
  `CREATED_BY` varchar(255) DEFAULT NULL,
  `UPDATED_TIME` datetime(6) DEFAULT NULL,
  `UPDATED_BY` varchar(255) DEFAULT NULL,
  `VULREPORTENUMS` varchar(225) DEFAULT NULL,
  `INPUTCONTENT` longtext
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- clouditera_aigc.REPORT_NOTICE definition

CREATE TABLE `REPORT_NOTICE` (
  `ID` varchar(64) DEFAULT NULL,
  `REPORT_NAME` varchar(255) DEFAULT NULL,
  `REPORT_DATE` datetime(6) DEFAULT NULL,
  `REPORT_PATH` longtext,
  `REPORT_STATUS` longtext,
  `CONTENT` longtext,
  `CREATED_TIME` datetime(6) DEFAULT NULL,
  `CREATED_BY` varchar(255) DEFAULT NULL,
  `UPDATED_TIME` datetime(6) DEFAULT NULL,
  `UPDATED_BY` varchar(255) DEFAULT NULL,
  `INPUTCONTENT` longtext
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- clouditera_aigc.REPORT_VUL definition

CREATE TABLE `REPORT_VUL` (
  `ID` varchar(64) DEFAULT NULL,
  `AIJUDGE_RESULT` longtext,
  `INFLUENCE_RANGE` longtext,
  `REPAIR_SUGGESTION` longtext,
  `DEVELOPMENT_PROCESS` longtext,
  `SCAN_VUL_ID` varchar(64) DEFAULT NULL,
  `CREATED_TIME` datetime(6) DEFAULT NULL,
  `CREATED_BY` varchar(255) DEFAULT NULL,
  `UPDATED_TIME` datetime(6) DEFAULT NULL,
  `UPDATED_BY` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- clouditera_aigc.REPO_INFO definition

CREATE TABLE `REPO_INFO` (
  `ID` varchar(64) NOT NULL,
  `CODE_SOURCE` varchar(16) DEFAULT NULL COMMENT '代码源',
  `REPO_TYPE` varchar(16) DEFAULT NULL COMMENT '仓库类型',
  `REPO_ADDRESS_URL` varchar(512) DEFAULT NULL COMMENT '仓库地址',
  `REPO_PRIVACY` tinyint DEFAULT NULL COMMENT '是否是公有仓库',
  `REPO_BRANCH` varchar(64) DEFAULT NULL COMMENT '仓库分支',
  `CERTIFICATE_TYPE` varchar(32) DEFAULT NULL COMMENT '凭证类型',
  `REPO_USERNAME` varchar(64) DEFAULT NULL COMMENT '用户名称',
  `REPO_PASSWORD` varchar(256) DEFAULT NULL COMMENT '用户密码',
  `CERT` text COMMENT '用户SSH',
  `CREATED_TIME` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `CREATED_BY` varchar(64) DEFAULT NULL COMMENT '创建人',
  `UPDATED_TIME` timestamp NULL DEFAULT NULL COMMENT '最后一次时间',
  `UPDATED_BY` varchar(64) DEFAULT NULL COMMENT '最后一次修改人',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- clouditera_aigc.SAFETY_INFORMATION definition

CREATE TABLE `SAFETY_INFORMATION` (
  `ID` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '主键ID',
  `CREATED_TIME` datetime(6) DEFAULT NULL COMMENT '创建时间',
  `CREATED_BY` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '创建人',
  `UPDATED_TIME` datetime(6) DEFAULT NULL COMMENT '更新时间',
  `UPDATED_BY` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '更新人',
  `ORIGINAL_CONTENT` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci COMMENT '资讯原文',
  `SUMMARY_CONTENT` text COLLATE utf8mb4_unicode_ci COMMENT '总结内容',
  `ORIGINAL_TITLE` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '原文标题',
  `SUMMARY_TITLE` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '总结标题',
  `ORIGINAL_URL` text COLLATE utf8mb4_unicode_ci COMMENT '原文链接',
  `RELEASE_TIME` datetime(6) DEFAULT NULL COMMENT '发布时间',
  `SOURCE_ID` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '来源ID',
  `PIC` text COLLATE utf8mb4_unicode_ci COMMENT '图片地址',
  `SUMMARY_STATUS` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '总结状态',
  `SUMMARY_COUNT` int DEFAULT NULL COMMENT '总结次数',
  `SCORE` float DEFAULT NULL COMMENT 'AI 评分',
  `ORIGINAL_CONTENT_LENGTH` int DEFAULT NULL COMMENT '原文长度',
  `SUMMARY_ONE_LINE` text COLLATE utf8mb4_unicode_ci COMMENT '一句话总结',
  `SUMMARY_EXCERPT` text COLLATE utf8mb4_unicode_ci COMMENT '总结摘要',
  `CRAWLER_ID` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '爬虫ID',
  PRIMARY KEY (`ID`),
  KEY `SAFETY_INFORMATION_SOURCE_ID_IDX` (`SOURCE_ID`) USING BTREE,
  KEY `SAFETY_INFORMATION_RELEASE_TIME_IDX` (`RELEASE_TIME`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='安全资讯表';


-- clouditera_aigc.SAFETY_INFORMATION_SCHEDULED_CONFIG definition

CREATE TABLE `SAFETY_INFORMATION_SCHEDULED_CONFIG` (
  `ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '主键ID',
  `LAST_TIME` datetime(6) DEFAULT NULL COMMENT '上一次执行时间',
  `CREATED_TIME` datetime(6) DEFAULT NULL COMMENT '创建时间',
  `CREATED_BY` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '创建人',
  `UPDATED_TIME` datetime(6) DEFAULT NULL COMMENT '更新时间',
  `UPDATED_BY` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '更新人',
  `ENABLED` tinyint DEFAULT NULL COMMENT '是否启用',
  `TYPE` varchar(10) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '定时器类型： QUERY、RETRY_SUMMARY',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='安全资讯定时任务配置表';


-- clouditera_aigc.SAFETY_INFORMATION_SOURCE definition

CREATE TABLE `SAFETY_INFORMATION_SOURCE` (
  `ID` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '主键ID',
  `NAME` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '名称',
  `SORT` int DEFAULT NULL COMMENT '排序',
  `CREATED_TIME` datetime(6) DEFAULT NULL,
  `CREATED_BY` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `UPDATED_TIME` datetime(6) DEFAULT NULL,
  `UPDATED_BY` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='安全资讯来源';


-- clouditera_aigc.SAFETY_INFORMATION_SOURCE_TYPE definition

CREATE TABLE `SAFETY_INFORMATION_SOURCE_TYPE` (
  `ID` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '主键ID',
  `NAME` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '名称',
  `SORT` int DEFAULT NULL COMMENT '排序',
  `CREATED_TIME` datetime(6) DEFAULT NULL COMMENT '创建时间',
  `CREATED_BY` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '创建人',
  `UPDATED_TIME` datetime(6) DEFAULT NULL COMMENT '更新时间',
  `UPDATED_BY` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- clouditera_aigc.SAFETY_INFORMATION_SOURCE_TYPE_REL definition

CREATE TABLE `SAFETY_INFORMATION_SOURCE_TYPE_REL` (
  `ID` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '主键ID',
  `SOURCE_ID` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '资讯源ID',
  `SOURCE_TYPE_ID` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '资讯源类型ID',
  `CREATED_TIME` datetime(6) DEFAULT NULL COMMENT '创建时间',
  `CREATED_BY` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '创建人',
  `UPDATED_TIME` datetime(6) DEFAULT NULL COMMENT '更新时间',
  `UPDATED_BY` varchar(65) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='安全资讯源与类型关联表';


-- clouditera_aigc.SAFETY_INFORMATION_TAG definition

CREATE TABLE `SAFETY_INFORMATION_TAG` (
  `ID` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '主键ID',
  `NAME` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '标签名称',
  `CREATED_TIME` datetime(6) DEFAULT NULL COMMENT '创建时间',
  `CREATED_BY` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '创建人',
  `UPDATED_TIME` datetime(6) DEFAULT NULL COMMENT '更新时间',
  `UPDATED_BY` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '更新人'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='安全资讯标签表';


-- clouditera_aigc.SAFETY_INFORMATION_TAG_REL definition

CREATE TABLE `SAFETY_INFORMATION_TAG_REL` (
  `ID` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '主键ID',
  `SAFETY_INFORMATION_ID` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '安全资讯ID',
  `SAFETY_INFORMATION_TAG_ID` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '安全资讯标签ID',
  `CREATED_TIME` datetime(6) DEFAULT NULL COMMENT '创建时间',
  `CREATED_BY` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '创建人',
  `UPDATED_TIME` datetime(6) DEFAULT NULL COMMENT '更新时间',
  `UPDATED_BY` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '更新人'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='安全资讯标签关联表';


-- clouditera_aigc.SAFETY_INFORMATION_TOPIC definition

CREATE TABLE `SAFETY_INFORMATION_TOPIC` (
  `ID` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '主键ID',
  `NAME` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '专题名称',
  `SORT` int DEFAULT NULL COMMENT '排序',
  `CREATED_TIME` datetime(6) DEFAULT NULL COMMENT '创建时间',
  `CREATED_BY` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '创建人',
  `UPDATED_TIME` datetime(6) DEFAULT NULL COMMENT '更新时间',
  `UPDATED_BY` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '更新人',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='安全资讯专题分类表';


-- clouditera_aigc.SAFETY_INFORMATION_TOPIC_REL definition

CREATE TABLE `SAFETY_INFORMATION_TOPIC_REL` (
  `ID` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '主键ID',
  `SAFETY_INFORMATION_ID` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '资讯ID',
  `SAFETY_INFORMATION_TOPIC_ID` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '专题ID',
  `CREATED_TIME` datetime(6) DEFAULT NULL COMMENT '创建时间',
  `CREATED_BY` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '创建人',
  `UPDATED_TIME` datetime(6) DEFAULT NULL COMMENT '更新时间',
  `UPDATED_BY` varchar(64) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='资讯专题关联表';


-- clouditera_aigc.SAST_JOB definition

CREATE TABLE `SAST_JOB` (
  `ID` varchar(64) DEFAULT NULL,
  `FILE_ID` varchar(64) DEFAULT NULL,
  `JOB_ADD_BY` varchar(64) DEFAULT NULL,
  `JOB_STATUS` varchar(200) DEFAULT NULL,
  `CREATED_TIME` timestamp NULL DEFAULT NULL,
  `CREATED_BY` varchar(64) DEFAULT NULL,
  `CHECK_START_TIME` timestamp NULL DEFAULT NULL,
  `CHECK_END_TIME` timestamp NULL DEFAULT NULL,
  `CODE_QUALITY_METRIC` text,
  `UPDATED_TIME` timestamp NULL DEFAULT NULL,
  `UPDATED_BY` varchar(64) DEFAULT NULL,
  `ENGINE_TYPE` varchar(225) DEFAULT NULL,
  `TYPE` varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- clouditera_aigc.SECURITY_LOOKOUT_TIME definition

CREATE TABLE `SECURITY_LOOKOUT_TIME` (
  `ID` varchar(64) NOT NULL COMMENT '主键',
  `CREATED_TIME` datetime(6) DEFAULT NULL,
  `CREATED_BY` varchar(255) DEFAULT NULL,
  `UPDATED_TIME` datetime(6) DEFAULT NULL,
  `UPDATED_BY` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- clouditera_aigc.SEC_PAPER_DATABASE definition

CREATE TABLE `SEC_PAPER_DATABASE` (
  `ID` varchar(64) NOT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `TIME` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- clouditera_aigc.SEC_PAPER_QUERY definition

CREATE TABLE `SEC_PAPER_QUERY` (
  `ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '主键',
  `QUERY` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '问题',
  `AHENT_ID` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT 'agentId',
  `DATABASE_IDS` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci COMMENT '相关数据库（会议/期刊/时间）',
  `CONTENT` text,
  `CREATED_TIME` datetime(6) DEFAULT NULL,
  `CREATED_BY` varchar(255) DEFAULT NULL,
  `UPDATED_TIME` datetime(6) DEFAULT NULL,
  `UPDATED_BY` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- clouditera_aigc.TOKEN definition

CREATE TABLE `TOKEN` (
  `ID` varchar(64) NOT NULL COMMENT 'ID',
  `UDER_ID` varchar(64) DEFAULT NULL COMMENT '用户ID',
  `TOKEN` bigint DEFAULT NULL COMMENT '消耗token数',
  `CREATED_TIME` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `CREATED_BY` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '创建人',
  `UPDATED_TIME` timestamp NULL DEFAULT NULL COMMENT '最后一次时间',
  `UPDATED_BY` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '最后一次修改人',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- clouditera_aigc.`USER` definition

CREATE TABLE `USER` (
  `ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '用户ID',
  `UNIONID` varchar(64) DEFAULT NULL COMMENT '微信用户唯一值',
  `USER_NAME` varchar(60) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '用户名',
  `USER_KEY` varchar(255) DEFAULT NULL COMMENT '密钥',
  `PHONE_NUMBER` varchar(11) DEFAULT NULL COMMENT '手机号',
  `WECHAT` text COMMENT '微信号',
  `OPEN_ID` varchar(64) DEFAULT NULL COMMENT '微信openID',
  `TOKEN` bigint DEFAULT NULL COMMENT '剩余token',
  `CREATED_TIME` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `CREATED_BY` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '创建人',
  `UPDATED_TIME` timestamp NULL DEFAULT NULL COMMENT '最后一次时间',
  `UPDATED_BY` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '最后一次修改人',
  `AUTO_PASSWORD` tinyint NOT NULL DEFAULT '1' COMMENT '自动密码',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- clouditera_aigc.USER_TOKEN_DETAIL definition

CREATE TABLE `USER_TOKEN_DETAIL` (
  `ID` varchar(64) NOT NULL,
  `USER_ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `GROUP_ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `AGENT_ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `EVENT` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `CONVERSATION_ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `MESSAGE_ID` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  `TOKENS` int DEFAULT '0',
  `CREATED_TIME` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `CREATED_BY` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '创建人',
  `UPDATED_TIME` timestamp NULL DEFAULT NULL COMMENT '最后一次时间',
  `UPDATED_BY` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '最后一次修改人',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- clouditera_aigc.VULNERABILITY_INFO definition

CREATE TABLE `VULNERABILITY_INFO` (
  `ID` varchar(64) NOT NULL COMMENT '主键',
  `BUG_ID` varchar(64) DEFAULT NULL COMMENT 'BUG_ID',
  `GROUP_ID` varchar(64) DEFAULT NULL COMMENT 'GROUP_ID',
  `FILE_PATH` varchar(512) DEFAULT NULL COMMENT '文件路径',
  `LINE` varchar(16) DEFAULT NULL COMMENT '所在行信息',
  `START_LINR` varchar(16) DEFAULT NULL COMMENT '起始行',
  `STOP_LINE` varchar(16) DEFAULT NULL COMMENT '结束行',
  `METHOD_NAME` varchar(512) DEFAULT NULL COMMENT '方法名称',
  `VARIABLE` varchar(512) DEFAULT NULL COMMENT '变量名称',
  `BUG_TYPE` varchar(32) DEFAULT NULL COMMENT 'bug类型',
  `MESSAGE` text COMMENT '描述信息',
  `WEAKNESS_LEVEL` varchar(32) DEFAULT NULL COMMENT '可利用性的等级',
  `STEPS` text COMMENT '污染路径',
  `FILE_ID` varchar(64) DEFAULT NULL COMMENT '文件ID',
  `BUG_STATE` varchar(64) DEFAULT NULL COMMENT '缺陷状态',
  `CREATED_TIME` timestamp NULL DEFAULT NULL COMMENT '创建时间',
  `CREATED_BY` varchar(64) DEFAULT NULL COMMENT '创建人',
  `UPDATED_TIME` timestamp NULL DEFAULT NULL COMMENT '最后一次时间',
  `UPDATED_BY` varchar(64) DEFAULT NULL COMMENT '最后一次修改',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- clouditera_aigc.VUL_DATABASE_RECORD definition

CREATE TABLE `VUL_DATABASE_RECORD` (
  `ID` varchar(64) NOT NULL,
  `TASK_ID` varchar(64) DEFAULT NULL,
  `CREATED_TIME` datetime(6) DEFAULT NULL,
  `CREATED_BY` varchar(255) DEFAULT NULL,
  `UPDATED_TIME` datetime(6) DEFAULT NULL,
  `UPDATED_BY` varchar(255) DEFAULT NULL,
  `PROGRESS_RATE` varchar(64) DEFAULT NULL,
  `TASK_STATUS` varchar(64) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;


-- clouditera_aigc.VUL_DOC_JOB definition

CREATE TABLE `VUL_DOC_JOB` (
  `YQ_ID` varchar(255) NOT NULL COMMENT 'YQ ID',
  `STATUS` varchar(255) DEFAULT NULL COMMENT '文件上传状态',
  `AGENT_TYPE` varchar(255) DEFAULT NULL,
  `DATASETS_ID` varchar(255) DEFAULT NULL,
  `BATCH` varchar(255) DEFAULT NULL,
  `DOCUMENT_ID` varchar(255) DEFAULT NULL,
  `CREATED_TIME` datetime(6) DEFAULT NULL,
  `CREATED_BY` varchar(255) DEFAULT NULL,
  `UPDATED_TIME` datetime(6) DEFAULT NULL,
  `UPDATED_BY` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`YQ_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;