-- 为 AI_SAST_TASK 表添加字段

ALTER TABLE `AI_SAST_TASK` 
ADD COLUMN `REPOSITORY_TYPE` enum('LOCAL','GIT') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '代码仓库类型（LOCAL/GIT）' AFTER `CONVERSATION_ID`,
ADD COLUMN `REPOSITORY_URL` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '代码仓库地址' AFTER `REPOSITORY_TYPE`,
ADD COLUMN `REPOSITORY_BRANCH` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '代码仓库分支' AFTER `REPOSITORY_URL`,
ADD COLUMN `FILE_SIZE` bigint DEFAULT NULL COMMENT '文件大小（字节）' AFTER `UPDATED_BY`,
ADD COLUMN `VULN_ARTIFACT_COUNT` int DEFAULT NULL COMMENT '检测出的漏洞数量统计' AFTER `FILE_SIZE`;

-- 删除旧的AI漏洞猎人智能体并新增
DELETE FROM clouditera_aigc.AGENT WHERE ID IN ('25', '26');
-- 新增AI漏洞猎人智能体
INSERT INTO clouditera_aigc.AGENT (ID, AGENT_NAME, WORKFLOW_NAME, AGENT_TYPE, TAG, PROMPT, APP_ID, FLAG, SORT, SHORTCUT, KL_STATUS, `KEY`, CREATED_TIME, CREATED_BY, UPDATED_TIME, UPDATED_BY, MODE_TYPE, CONFIG, VERSION, STATUS, TYPE, COUNT_TOKENS, COMMON_HOME, COMMON_CONVERSATION, COMMON_QUESTION, PARENT_ID, AGENT_METADATA) VALUES ('25', 'AI漏洞猎人', '代码漏洞', 'COMMON', 'COMMON', null, null, 1, null, 0, 0, '', null, null, '2025-08-21 11:16:08', '714a9a60-831d-431d-b918-d2e8c90ae3b0', null, null, '1.0', 'AGENT_ALPHA', 'CODE', 1, 1, 1, 1, null, '{"path":null}');
