-- 为 AI_SAST_TASK 表添加字段

ALTER TABLE `AI_SAST_TASK` 
ADD COLUMN `REPOSITORY_TYPE` enum('LOCAL','GIT') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '代码仓库类型（LOCAL/GIT）' AFTER `CONVERSATION_ID`,
ADD COLUMN `REPOSITORY_URL` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '代码仓库地址' AFTER `REPOSITORY_TYPE`,
ADD COLUMN `REPOSITORY_BRANCH` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '代码仓库分支' AFTER `REPOSITORY_URL`,
ADD COLUMN `FILE_SIZE` bigint DEFAULT NULL COMMENT '文件大小（字节）' AFTER `UPDATED_BY`,
ADD COLUMN `VULN_ARTIFACT_COUNT` int DEFAULT NULL COMMENT '检测出的漏洞数量统计' AFTER `FILE_SIZE`;